LOCAL_IP = "***REMOVED***"

SR_IP = "***REMOVED***"
SR_READ_PORT = ***REMOVED***
SR_WRITE_PORT = ***REMOVED***

MULTICAST_IP = '***REMOVED***'
MULTICAST_PORT = ***REMOVED***
BUFFER_SIZE = ***REMOVED***

UDP_CLIENT_PORT = ***REMOVED***


USE_TEST_SERVER = True